---
pipeline:
  processors:
    - bloblang: |
        root.body = "{\"data\":\"TODO\"}"
        root.statusCode = 200
    - resource: worker_lambda
    - bloblang: |
        root = if meta().exists("lambda_function_error") {
          throw("Invocation failed due to %v: %v".format(this.errorType, this.errorMessage))
        } else {
          this
        }
    - log:
        message: 'Error: ${! error() }'

output:
  switch:
    cases:
      - check: errored()
        output:
          reject: ${! error() }
      - output:
          sync_response: {}

resources:
  processors:
    worker_lambda:
      aws_lambda:
        region: ${AWS_REGION}
        function: ${WORKER_LAMBDA:'null'}

logger:
  level: ${LOG_LEVEL:info}
  static_fields:
    functionName: ${AWS_LAMBDA_FUNCTION_NAME:''}
    version: ${LOG_VERSION:''}
