---
pipeline:
  processors:
    - bloblang: |
        root.body = "{\"data\":\"TODO\"}"
        root.statusCode = 200

output:
  broker:
    pattern: fan_out_sequential
    outputs:
      - http_client:
          url: http://localhost:1234/this/url/always/fails
          timeout: 2s
      - type: serverless_response

logger:
  level: ${LOG_LEVEL:info}
  static_fields:
    functionName: ${AWS_LAMBDA_FUNCTION_NAME:''}
    version: ${LOG_VERSION:''}
