---
name: version

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to cut
  repository_dispatch:
    types:
      - version

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup Git config
        env:
          GH_USER: ${{ secrets.GH_USER }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        run: |
          git remote set-url --push origin "https://${GH_USER}:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git config user.name "$GIT_USER_NAME"
          git config user.email "$GIT_USER_EMAIL"
          npm config set sign-git-tag true
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        id: import_gpg
        with:
          git-user-signingkey: true
          git-commit-gpgsign: true
          git-committer-name: ${{ secrets.GIT_USER_NAME }}
          git-committer-email: ${{ secrets.GIT_USER_EMAIL }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Get yarn cache directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Node modules cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: Download Benthos
        run: |
          benthos_version="$(jq -r .benthos.version < package.json)"
          benthos_src="$(jq -r .benthos.src < package.json)/v${benthos_version}"
          curl -fsSL --create-dirs -o \
            tmp/benthos.tar.gz "${benthos_src}/benthos_${benthos_version}_linux_amd64.tar.gz"
          curl -fsSL -o tmp/benthos_checksums.txt \
            "${benthos_src}/benthos_${benthos_version}_checksums.txt"
          cd tmp
          sha256sum --strict --ignore-missing --check benthos_checksums.txt
      - name: Install Benthos to PATH
        run: |
          cd tmp
          tar -xzf benthos.tar.gz
          mkdir -p bin
          mv benthos bin
          echo "$(pwd)/bin" >> $GITHUB_PATH
      - name: Cut ${{ github.event.inputs.version }}${{ github.event.client_payload.version }} version
        run: npm version ${{ github.event.inputs.version }}${{ github.event.client_payload.version }}
